Este pueblo... De alguna forma, es al mismo tiempo pacífico y agotador...
A ver que me ha preparado la mujer de la posada esta noche...
...
.....
Está muy rico... La carne es... Tiene un tacto diferente, no he comido nada igual.
Bueno, me voy a dormir... Mañana será otro día.