Resulta que esta parada causada por la avería de mi vehículo era en realidad la clave para resolver el misterio...
Tenía la intención de publicar cualquier descubrimiento que hiciera, pero...
Han sido unos días muy especiales, y prefiero protegerles
De alguna forma, les he cogido cariño...
Hay tantas cosas que puedo descubrir pasando tiempo aqui...
...
Volveré pronto